export  const LOAD_ALL_TODOS_SUCCESS = 'LOAD_ALL_TODOS_SUCCESS';
export  const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export  const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export  const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";
